"""Core domain layer of the Discord/Telegram suggest bridge.

Platform adapters (aiogram, discord.py) build on this package: they call
services, subscribe to domain events and never touch SQL directly.
"""

from __future__ import annotations

from bot.core.approve_flow import ApprovalOutcome, finalize_approval
from bot.core.db import (
    DEFAULT_BRIDGE_DB_PATH,
    BridgeDatabase,
    resolve_bridge_db_path,
)
from bot.core.events import EventBus
from bot.core.models import (
    Admin,
    AdminChanged,
    BlacklistEntry,
    ContentType,
    DomainEvent,
    GuildConfig,
    MediaItem,
    MirrorKind,
    MirrorLink,
    ModerationRef,
    Platform,
    PublishTarget,
    RefKind,
    Source,
    Submission,
    SubmissionApproved,
    SubmissionCreated,
    SubmissionPublished,
    SubmissionRejected,
    SubmissionScheduled,
    SubmissionStatus,
    SubmissionSubmitted,
    SubmissionUpdated,
    UserBlocked,
    UserUnblocked,
    utcnow,
)
from bot.core.publish_router import (
    DualPublishResult,
    PublishRouter,
    PublishRouterError,
    is_mirror_enabled,
    set_mirror_enabled,
)
from bot.core.publisher import (
    PublishMedia,
    PublishMode,
    PublishPlan,
    build_publish_plan,
    extract_publish_ref,
    resolve_with_author,
)
from bot.core.rules import (
    ANON_NAME,
    HASHTAG,
    TEXT_LIMIT,
    build_channel_caption,
    can_transition,
    ensure_transition,
    is_handled,
    is_terminal,
    validate_text,
)
from bot.core.scheduler import (
    DEFAULT_BATCH_LIMIT,
    DEFAULT_POLL_INTERVAL_SEC,
    PublishCallback,
    Scheduler,
)
from bot.core.host_lease import (
    ConsentDeniedError,
    EXIT_CONSENT_DENIED,
    EXIT_LEASE_HELD,
    HostLeaseError,
    HostLeaseStatus,
    LeaseHeldError,
    claim as claim_host_lease,
    grant_consent,
    heartbeat_loop,
    is_primary as is_host_primary,
    release as release_host_lease,
    renew as renew_host_lease,
    resolve_host_id,
    revoke_consent,
    status as host_lease_status,
    write_lease,
)
from bot.core.host_control import (
    HostControlError,
    HostPanelSnapshot,
    TransferRequest,
    is_owner_discord,
    is_owner_telegram,
    owner_discord_id,
    owner_telegram_id,
    panel_snapshot,
)
from bot.core.host_sync import (
    HostAck,
    HostCommand,
    HostRegistryEntry,
    HostSyncStore,
    resolve_sync_dir,
)
from bot.core.services import (
    DEFAULT_ANTIFLOOD_LIMIT,
    DEFAULT_ANTIFLOOD_WINDOW_SEC,
    AdminService,
    AntifloodDecision,
    AntifloodService,
    BlacklistService,
    GuildConfigService,
    ModerationResult,
    ModerationService,
    SubmissionNotFoundError,
    SubmissionService,
)

__all__ = [
    # storage
    "BridgeDatabase",
    "DEFAULT_BRIDGE_DB_PATH",
    "resolve_bridge_db_path",
    # host lease / control
    "ConsentDeniedError",
    "EXIT_CONSENT_DENIED",
    "EXIT_LEASE_HELD",
    "HostControlError",
    "HostLeaseError",
    "HostLeaseStatus",
    "HostPanelSnapshot",
    "HostAck",
    "HostCommand",
    "HostRegistryEntry",
    "HostSyncStore",
    "LeaseHeldError",
    "TransferRequest",
    "claim_host_lease",
    "grant_consent",
    "heartbeat_loop",
    "host_lease_status",
    "is_host_primary",
    "is_owner_discord",
    "is_owner_telegram",
    "owner_discord_id",
    "owner_telegram_id",
    "panel_snapshot",
    "release_host_lease",
    "renew_host_lease",
    "resolve_host_id",
    "resolve_sync_dir",
    "revoke_consent",
    "write_lease",
    # events
    "EventBus",
    "DomainEvent",
    "SubmissionCreated",
    "SubmissionUpdated",
    "SubmissionSubmitted",
    "SubmissionApproved",
    "SubmissionRejected",
    "SubmissionScheduled",
    "SubmissionPublished",
    "AdminChanged",
    "UserBlocked",
    "UserUnblocked",
    # models
    "Admin",
    "BlacklistEntry",
    "ContentType",
    "GuildConfig",
    "MediaItem",
    "MirrorKind",
    "MirrorLink",
    "ModerationRef",
    "Platform",
    "PublishTarget",
    "RefKind",
    "Source",
    "Submission",
    "SubmissionStatus",
    "utcnow",
    # rules
    "ANON_NAME",
    "HASHTAG",
    "TEXT_LIMIT",
    "build_channel_caption",
    "can_transition",
    "ensure_transition",
    "is_handled",
    "is_terminal",
    "validate_text",
    # publishing
    "DualPublishResult",
    "PublishMedia",
    "PublishMode",
    "PublishPlan",
    "PublishRouter",
    "PublishRouterError",
    "build_publish_plan",
    "extract_publish_ref",
    "is_mirror_enabled",
    "resolve_with_author",
    "set_mirror_enabled",
    # approve / schedule flow
    "ApprovalOutcome",
    "finalize_approval",
    "DEFAULT_BATCH_LIMIT",
    "DEFAULT_POLL_INTERVAL_SEC",
    "PublishCallback",
    "Scheduler",
    # services
    "AdminService",
    "AntifloodDecision",
    "AntifloodService",
    "BlacklistService",
    "DEFAULT_ANTIFLOOD_LIMIT",
    "DEFAULT_ANTIFLOOD_WINDOW_SEC",
    "GuildConfigService",
    "ModerationResult",
    "ModerationService",
    "SubmissionNotFoundError",
    "SubmissionService",
]
